import { GoogleGenerativeAI } from '@google/generative-ai';

// System Prompts for each specialized Agent
export const AGENT_PROMPTS = {
  researcher: {
    name: 'Researcher Agent',
    role: 'Information Gathering & Outline Creation',
    color: '#3b82f6', // blue
    systemInstruction: `You are the Resource & Researcher Agent. Your job is to gather relevant facts, structural outline, key points, and sources for the requested task.
Focus on factuality, comprehensive coverage, and logical structure. 
Provide your response in a clear markdown structure with sections: 
1. Key Themes & Information
2. Detailed Outline
3. Recommended References/Facts
Do not write the final draft itself. Only provide the research material.`,
  },
  writer: {
    name: 'Writer Agent',
    role: 'Content Draft Generation',
    color: '#a855f7', // purple
    systemInstruction: `You are the Content Writer Agent. Your job is to write a high-quality draft based on the research provided by the Researcher Agent.
Adhere strictly to the requested task guidelines and incorporate the outline/facts provided by the researcher.
If this is a revision, you will also receive critique/feedback from the Reviewer Agent. You must address their feedback completely in your new draft.
Provide a complete, polished draft in Markdown format.`,
  },
  reviewer: {
    name: 'Reviewer Agent',
    role: 'Quality Assurance & Critique',
    color: '#10b981', // green
    systemInstruction: `You are the Reviewer/QA Agent. Your job is to critique the draft generated by the Writer Agent, comparing it against the original task and the research details.
Analyze readability, structure, factual correctness, and style.
You must output a response in JSON format (or markdown with a clear JSON block at the bottom) with the following structure:
{
  "approved": true or false,
  "rating": 1 to 5,
  "feedback": "Detailed critique of the draft, listing specific areas that need improvement if not approved, or praising the draft if approved."
}
If approved is false, be constructive and demanding, pointing out exactly what the writer should improve. Do not approve until it is genuinely excellent.`,
  }
};

// Orchestrate the collaborative loop
export async function runCollaboration({ task, apiKey, modelName = 'gemini-1.5-flash', onStepUpdate, maxIterations = 3 }) {
  let step = 0;
  let currentStatus = 'starting';
  
  const logs = [];
  const addLog = (agent, action, content, data = {}) => {
    const logEntry = {
      id: Date.now() + Math.random().toString(36).substr(2, 9),
      timestamp: new Date().toLocaleTimeString(),
      agent,
      action,
      content,
      ...data
    };
    logs.push(logEntry);
    if (onStepUpdate) {
      onStepUpdate({ logs: [...logs], currentStatus, step });
    }
  };

  // Mock responses for simulation mode when apiKey is not provided
  if (!apiKey) {
    currentStatus = 'simulating_research';
    addLog('Researcher Agent', 'Gathering resources and structured data...', 'Searching repository, verifying sources, and building information structure...');
    await new Promise(r => setTimeout(r, 2000));
    
    const mockResearch = `# Research Report: ${task}
1. Key Themes & Information:
   - Primary goals of "${task}" and its target audience.
   - Historical context and modern relevance.
   - Structural design concepts and core arguments.
2. Detailed Outline:
   - Introduction: Core thesis definition.
   - Main Body: Deep-dive analysis and evidence.
   - Counter-perspective / Alternative views.
   - Conclusion: Strategic summary.
3. Recommended References/Facts:
   - Fact A: Crucial underlying data supporting the thesis.
   - Fact B: Contextual studies showing impact.`;
    
    addLog('Researcher Agent', 'Completed research outline', mockResearch, { type: 'research' });
    
    // Writer step
    currentStatus = 'simulating_writing';
    step = 1;
    addLog('Writer Agent', 'Drafting initial content...', `Developing draft using researcher's outline for: "${task}"...`);
    await new Promise(r => setTimeout(r, 2500));
    
    const mockDraft1 = `# Comprehensive Draft: ${task}

This is the initial draft generated to address: "${task}".

## Introduction
The context of ${task} represents a significant milestone in modern technology and system design. By establishing clear design principles, we can achieve high performance and ease of use.

## Core Analysis
Initial points suggest a multi-layered approach. However, some elements might require deeper analysis in the next revision.

## Conclusion
In summary, we have established a strong baseline draft, pending review.`;

    addLog('Writer Agent', 'Generated initial draft', mockDraft1, { type: 'draft' });

    // Reviewer step (Reject first for demonstration of collaboration)
    currentStatus = 'simulating_reviewing';
    step = 2;
    addLog('Reviewer Agent', 'Critiquing draft...', 'Evaluating readability, accuracy, and flow of the draft...');
    await new Promise(r => setTimeout(r, 2000));

    const reviewerFeedback1 = `The introduction is too brief and fails to captivate the reader. The "Core Analysis" section is extremely vague and needs specific examples and data points. Please expand on the core mechanisms and make it sound more professional.`;
    
    addLog('Reviewer Agent', 'Rejected draft (Requested revisions)', `Decision: REJECTED\nRating: 2/5\n\nFeedback: ${reviewerFeedback1}`, {
      type: 'review',
      approved: false,
      rating: 2
    });

    // Writer step 2 (Revision)
    currentStatus = 'simulating_writing_revision';
    step = 3;
    addLog('Writer Agent', 'Revising draft based on feedback...', 'Addressing Reviewer comments: expanding intro and body sections...');
    await new Promise(r => setTimeout(r, 2500));

    const mockDraft2 = `# Collaborative Report: ${task}

## Introduction
In the rapidly evolving landscape, "${task}" stands as a critical paradigm shift. This report offers a comprehensive examination of its architectural patterns, optimization pathways, and practical applications, illustrating why it has captured industry-wide interest.

## Core Analysis & Mechanisms
To understand "${task}", we must analyze its fundamental components:
1. **Dynamic Scheduling**: Maximizing throughput by allocating tasks in real-time.
2. **Context Isolation**: Minimizing conflicts and memory overhead by maintaining clean sandboxes.
3. **Collaboration Protocols**: Facilitating seamless message passing and feedback loops.

Our quantitative benchmarks indicate a 35% reduction in latency and a 2x increase in throughput compared to traditional systems.

## Conclusion
By adopting this sophisticated multi-agent paradigm, developers can unlock unparalleled scaling potential. The synergy between researcher, writer, and reviewer agents forms the cornerstone of autonomous document generation.`;

    addLog('Writer Agent', 'Generated revised draft', mockDraft2, { type: 'draft' });

    // Reviewer step 2 (Approve)
    currentStatus = 'simulating_reviewing_final';
    step = 4;
    addLog('Reviewer Agent', 'Performing final quality check...', 'Analyzing revisions and checkmarks against initial outline...');
    await new Promise(r => setTimeout(r, 2000));

    addLog('Reviewer Agent', 'Approved draft!', 'Decision: APPROVED\nRating: 5/5\n\nFeedback: Excellent revisions! The introduction is compelling, the core analysis is detailed with solid points and numbers, and the conclusion is impactful. Outstanding collaborative output.', {
      type: 'review',
      approved: true,
      rating: 5,
      finalOutput: mockDraft2
    });

    currentStatus = 'completed';
    if (onStepUpdate) {
      onStepUpdate({ logs: [...logs], currentStatus, step, finalOutput: mockDraft2 });
    }
    return;
  }

  // Real LLM Collaboration
  try {
    const ai = new GoogleGenerativeAI(apiKey);
    
    // 1. RESEARCH STATE
    currentStatus = 'researching';
    addLog('Researcher Agent', 'Gathering research and outlines...', `Starting research on task: "${task}"...`);
    
    const researchModel = ai.getGenerativeModel({
      model: modelName,
      systemInstruction: AGENT_PROMPTS.researcher.systemInstruction,
    });
    
    const researchResult = await researchModel.generateContent(`Generate research and an outline for: "${task}"`);
    const researchText = researchResult.response.text();
    addLog('Researcher Agent', 'Completed research outline', researchText, { type: 'research' });

    let currentDraft = '';
    let feedbackLoopCount = 0;
    let reviewerDecision = { approved: false, feedback: 'No review yet.' };

    while (!reviewerDecision.approved && feedbackLoopCount < maxIterations) {
      feedbackLoopCount++;
      step = feedbackLoopCount;

      // 2. WRITING STATE
      currentStatus = `writing_iteration_${feedbackLoopCount}`;
      addLog('Writer Agent', `Drafting content (Iteration ${feedbackLoopCount})...`, 
        feedbackLoopCount === 1 
          ? `Writing initial draft...` 
          : `Revising draft based on reviewer feedback...`
      );

      const writerModel = ai.getGenerativeModel({
        model: modelName,
        systemInstruction: AGENT_PROMPTS.writer.systemInstruction,
      });

      const writerPrompt = feedbackLoopCount === 1
        ? `Task: "${task}"\n\nResearch material to use:\n${researchText}`
        : `Task: "${task}"\n\nResearch material:\n${researchText}\n\nPrevious Draft:\n${currentDraft}\n\nReviewer Feedback:\n${reviewerDecision.feedback}\n\nPlease revise the draft to fully address the feedback.`;

      const writerResult = await writerModel.generateContent(writerPrompt);
      currentDraft = writerResult.response.text();
      addLog('Writer Agent', `Generated draft (Iteration ${feedbackLoopCount})`, currentDraft, { type: 'draft' });

      // 3. REVIEWING STATE
      currentStatus = `reviewing_iteration_${feedbackLoopCount}`;
      addLog('Reviewer Agent', `Critiquing draft (Iteration ${feedbackLoopCount})...`, `Evaluating quality and alignment of the draft...`);

      const reviewerModel = ai.getGenerativeModel({
        model: modelName,
        systemInstruction: AGENT_PROMPTS.reviewer.systemInstruction,
      });

      const reviewerPrompt = `Original Task: "${task}"\n\nResearch Materials:\n${researchText}\n\nWriter's Draft:\n${currentDraft}\n\nEvaluate the draft. You must decide whether it is fully approved or if it needs revisions. Provide your review.`;

      const reviewerResult = await reviewerModel.generateContent(reviewerPrompt);
      const reviewerText = reviewerResult.response.text();

      // Try to parse JSON from the response
      try {
        const jsonMatch = reviewerText.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          reviewerDecision = JSON.parse(jsonMatch[0]);
        } else {
          // fallback parser if not perfectly formatted JSON
          const isApproved = reviewerText.toLowerCase().includes('"approved": true') || reviewerText.toLowerCase().includes('approved: true');
          reviewerDecision = {
            approved: isApproved,
            feedback: reviewerText
          };
        }
      } catch (e) {
        reviewerDecision = {
          approved: reviewerText.toLowerCase().includes('approve'),
          feedback: reviewerText
        };
      }

      addLog('Reviewer Agent', reviewerDecision.approved ? 'Approved draft!' : 'Rejected draft (Requested revisions)', 
        `Approved: ${reviewerDecision.approved ? 'YES' : 'NO'}\n\nFeedback:\n${reviewerDecision.feedback}`, {
        type: 'review',
        approved: reviewerDecision.approved,
        rating: reviewerDecision.rating || (reviewerDecision.approved ? 5 : 3)
      });
    }

    currentStatus = 'completed';
    if (onStepUpdate) {
      onStepUpdate({ logs: [...logs], currentStatus, step, finalOutput: currentDraft });
    }
  } catch (error) {
    addLog('System Error', 'Error during collaboration flow', error.message, { isError: true });
    currentStatus = 'failed';
    if (onStepUpdate) {
      onStepUpdate({ logs: [...logs], currentStatus, step });
    }
  }
}

// Chatbot Assistant runner
export async function runChatAssistant({ message, history, finalOutput, apiKey, modelName = 'gemini-1.5-flash' }) {
  if (!apiKey) {
    // Simulated responses
    await new Promise(r => setTimeout(r, 1000));
    const userMsg = message.toLowerCase();
    
    if (userMsg.includes('hello') || userMsg.includes('hi')) {
      return "Hello! I am the Coordinator chatbot. I can help you analyze the generated document, explain what the agents did, or discuss tasks. How can I assist you today?";
    }
    if (userMsg.includes('summarize') || userMsg.includes('summary')) {
      return finalOutput 
        ? `Here is a summary of the generated document:\n\nThe document details the user's task. It includes an introductory section highlighting key concepts, an in-depth analysis detailing key mechanisms (dynamic scheduling, context isolation, and collaboration protocols), and a strategic conclusion. Let me know if you want me to expand on any particular part!`
        : "No document has been generated yet. Please run the agent loop first, and then I can summarize it for you!";
    }
    if (userMsg.includes('agent') || userMsg.includes('who')) {
      return "The collaboration engine consists of three agents:\n1. **Researcher Agent** (blue): Conducts the research and outlines structure.\n2. **Writer Agent** (purple): Composes and refines the draft.\n3. **Reviewer Agent** (green): Inspects quality, rates it, and approves/rejects.";
    }
    return `This is a simulated chatbot response. I received your message: "${message}". If you add a Gemini API key in the configuration panel, you can chat with me live and ask any questions about the generated draft!`;
  }

  try {
    const ai = new GoogleGenerativeAI(apiKey);
    const model = ai.getGenerativeModel({
      model: modelName,
      systemInstruction: `You are the Coordinator Assistant chatbot for the Multi-Agent Collaboration system.
Your job is to assist the user by answering questions about the generated document, explaining the agent actions, or offering suggestions.
Context of the generated document:
${finalOutput || 'No document generated yet.'}

Be helpful, concise, and professional.`,
    });

    // Format chat history for Gemini API
    const contents = history.map(msg => ({
      role: msg.sender === 'user' ? 'user' : 'model',
      parts: [{ text: msg.text }]
    }));
    
    contents.push({
      role: 'user',
      parts: [{ text: message }]
    });

    const result = await model.generateContent({ contents });
    return result.response.text();
  } catch (error) {
    return `Error from Chatbot: ${error.message}`;
  }
}

